### ISSUE TITLE
Contribute a Development Resource

### ISSUE THREAD

**Issue by nataliepina** [nataliepina/Development-Resources#1]
# Happy Hacktoberfest 🎃 

I am creating a growing list of the best resources for development. Contributions are welcome! 
This is a great safe space for first-time open-source developers to test out open-source contributions.

### How to Contribute 
1. Fork it.
2. Clone it to your local system.
3. Make a new branch.
4. Make your changes.
5. Push it back to your repo.
6. Click the Compare & pull request button.
7. Click Create pull request to open a new pull request.

**Comment by xoxo16** [comment]
pls assign this issue to me

**Comment by lotfijb** [comment]
can you please assign me this issue

**Comment by nataliepina** [comment]
I'm leaving this up as an open invitation for anyone to contribute. Feel free to fork the repository and add as many resources as you'd like.

**Comment by lotfijb** [comment]
what is wrong with my request so i can fix it please ?
